/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openthos_seafile_JNI */

#ifndef _Included_org_openthos_seafile_JNI
#define _Included_org_openthos_seafile_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openthos_seafile_JNI
 * Method:    nativeKill
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_org_openthos_seafile_Jni_nativeKillPid
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
