#!/bin/sh

## Accounts
tar -czvf /data/data/temp/accounts.tar.gz /data/system/users/0/accounts.db*

## Fennec
mkdir -p /data/data/temp/org.mozilla.fennec_openthos/files/mozilla/openthos.default
cp -rv /data/data/org.mozilla.fennec_openthos/databases /data/data/temp/org.mozilla.fennec_openthos
cp -rv /data/data/org.mozilla.fennec_openthos/shared_prefs/ /data/data/temp/org.mozilla.fennec_openthos
cp -rv /data/data/org.mozilla.fennec_openthos/files/mozilla/profiles.ini /data/data/temp/org.mozilla.fennec_openthos/files/mozilla
cp -v /data/data/org.mozilla.fennec_openthos/files/mozilla/openthos.default/* /data/data/temp/org.mozilla.fennec_openthos/files/mozilla/openthos.default/
tar -czvf /data/data/temp/org.mozilla.fennec_openthos.tar.gz -C /data/data/temp/ org.mozilla.fennec_openthos
rm -r /data/data/temp/org.mozilla.fennec_openthos/

## File Preference
tar -czvf /data/data/temp/preference.tar.gz /data/system/users/0/package-restrictions.xml

## Language
echo "language=`getprop persist.sys.language`" > /data/data/temp/language.conf
echo "country=`getprop persist.sys.country`" >> /data/data/temp/language.conf

## Security
tar -czvf /data/data/temp/security.tar.gz /data/system/locksettings.db* /data/system/password.key

## Settings
tar -czvf /data/data/temp/com.android.settings.tar.gz -C /data/data/ com.android.settings

## Settings Providers
tar -czvf /data/data/temp/com.android.providers.settings.tar.gz -C /data/data/ com.android.providers.settings

## SystemUI
tar -czvf /data/data/temp/com.android.systemui.tar.gz -C /data/data/ com.android.systemui

## Wifi
tar -czvf /data/data/temp/wifi.tar.gz /data/misc/wifi

## tar
tar -cvf /data/data/temp/$1.tar -C /data/data/ temp
chmod 755 /data/data/temp/$1.tar

## move
cp /data/data/temp/$1.tar $2

## Wallpaper  only one
if [ -f /data/system/users/0/wallpaper ];then
	tar -czvf /data/data/temp/wallpaper.tar.gz /data/system/users/0/wallpaper
	chmod 755 /data/data/temp/wallpaper.tar.gz
	cp /data/data/temp/wallpaper.tar.gz $2
fi

## clean
rm /data/data/temp/*
